# Generated by Django 5.1.1 on 2024-10-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchDesc', models.CharField(max_length=200)),
                ('branchAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('start', models.DateTimeField(unique=True)),
                ('end', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('firstname', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('dateofbirth', models.DateField()),
                ('employmentdate', models.DateField()),
                ('designation', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phonenumber', models.IntegerField(unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_branch', to='setup.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageDesc', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_branch', to='setup.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupmDesc', models.CharField(max_length=100)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_storage', to='setup.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_storage', to='setup.storage')),
            ],
        ),
    ]
