# Generated by Django 5.1.1 on 2024-10-31 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=200, unique=True)),
                ('branchAddress', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100, unique=True)),
                ('productDescription', models.CharField(default='None', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_product', to='setup.product')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('firstname', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('dateofbirth', models.DateField()),
                ('sex', models.CharField(db_index=True, default=1, max_length=10)),
                ('employmentdate', models.DateField()),
                ('designation', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phonenumber', models.BigIntegerField(unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_branch', to='setup.branch')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageDesc', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_branch', to='setup.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_product', to='setup.product')),
            ],
            options={
                'verbose_name_plural': 'Storage',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pumpDesc', models.CharField(default='None', max_length=100)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_storage', to='setup.storage')),
            ],
            options={
                'verbose_name_plural': 'Pump',
            },
        ),
    ]
