# Generated by Django 5.1.1 on 2024-10-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='capacity',
            new_name='quantity',
        ),
    ]
