# Generated by Django 5.1.1 on 2024-10-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_rename_capacity_storage_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branchDesc',
            new_name='branchName',
        ),
    ]
