# Generated by Django 5.1.1 on 2024-10-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_rename_branchdesc_branch_branchname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'verbose_name_plural': 'Pump'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name_plural': 'Shift'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name_plural': 'Storage'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
