# Generated by Django 5.1.1 on 2024-10-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_rename_type_product_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_product', to='setup.product'),
            preserve_default=False,
        ),
    ]
