# Generated by Django 5.1.1 on 2024-10-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_storage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_pump', to='setup.pump'),
        ),
        migrations.AddField(
            model_name='shift',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_staff', to='setup.staff'),
        ),
        migrations.AddField(
            model_name='shift',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.CharField(db_index=True, default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pupmDesc',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
