# Generated by Django 5.1.1 on 2024-10-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_shift_is_active_shift_pump_shift_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_pump', to='setup.pump'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_staff', to='setup.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(db_index=True, default=1, max_length=10),
        ),
    ]
