# Generated by Django 5.1.1 on 2024-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_shift_pump_alter_shift_staff_alter_staff_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pupmDesc',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
