# Generated by Django 5.1.1 on 2024-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_alter_pump_pupmdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phonenumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
