# Generated by Django 5.1.1 on 2024-10-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_staff_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='pupmDesc',
            new_name='pumpDesc',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_product', to='setup.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
