# Generated by Django 5.1.1 on 2024-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_rename_pupmdesc_pump_pumpdesc_price_delete_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
