# Generated by Django 5.1.1 on 2024-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_rename_name_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
