# Generated by Django 5.1.1 on 2024-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_rename_username_user_phone_number_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
