# Generated by Django 5.1.1 on 2024-11-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorysnapshot',
            old_name='inventoryv',
            new_name='inventory',
        ),
    ]
