# Generated by Django 5.1.1 on 2024-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventoryv_inventorysnapshot_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='dateUpdated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
