# Generated by Django 5.1.1 on 2024-12-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_dateupdated_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='updatedBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='setup.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
    ]
