# Generated by Django 5.1.1 on 2024-12-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorysnapshot_updatedby_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysnapshot',
            options={'verbose_name_plural': 'Inventory History'},
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.staff'),
        ),
    ]
