# Generated by Django 5.1.1 on 2024-12-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorysnapshot_inventory_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.branch'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_product', to='setup.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.storage'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.staff'),
        ),
    ]
