# Generated by Django 5.1.1 on 2024-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_branch_alter_inventory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='product',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='updatedBy',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
