# Generated by Django 5.1.1 on 2024-12-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorysnapshot_product_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.product'),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.staff'),
        ),
    ]
