# Generated by Django 5.1.1 on 2024-10-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=520)),
                ('enable', models.BooleanField(default=False)),
                ('password_count', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='setup.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Active', models.BooleanField(default=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggedin', to='validation.user')),
            ],
        ),
    ]
