# Generated by Django 5.1.1 on 2024-10-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_rename_capacity_storage_quantity'),
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginTable',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserTable',
        ),
        migrations.AlterModelOptions(
            name='logintable',
            options={'verbose_name_plural': 'LoginTable'},
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={'verbose_name_plural': 'UserTable'},
        ),
    ]
