# Generated by Django 5.1.1 on 2024-10-31 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expected_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_branch', to='setup.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_product', to='setup.product')),
                ('pump', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_pump', to='setup.pump')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_staff', to='setup.staff')),
            ],
            options={
                'verbose_name_plural': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expected_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reconciliation', models.BooleanField(default=True)),
                ('remark', models.TextField(max_length=1000, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_shift', to='sales.shift')),
            ],
        ),
    ]
