# Generated by Django 5.1.1 on 2024-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
