# Generated by Django 5.1.1 on 2024-11-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='actual_sales',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='expected_sales',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='quantity_sold',
        ),
    ]
