# Generated by Django 5.1.1 on 2024-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_shift_actual_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
