# Generated by Django 5.1.1 on 2024-11-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_shift_branch_remove_shift_product_and_more'),
    ]

    operations = [
    ]
