# Generated by Django 5.1.1 on 2024-11-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_migrate_shift_data'),
    ]

    operations = [
    ]
