# Generated by Django 5.1.1 on 2024-11-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_migrate_shift_data'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_branch', to='setup.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_product', to='setup.product'),
        ),
    ]
