# Generated by Django 5.1.1 on 2024-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_shift_branch_shift_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='stock',
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
