# Generated by Django 5.1.1 on 2024-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_shift_branch_remove_shift_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('On-Going', 'On-Going'), ('Pending', 'Pending'), ('Ended', 'Ended')], default='Pending', max_length=100, verbose_name='STatus'),
            preserve_default=False,
        ),
    ]
