# Generated by Django 5.1.1 on 2024-11-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_shift_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='reconciliation',
            field=models.CharField(choices=[('Reconciled', 'Reconciled'), ('Pending', 'Pending')], max_length=100, verbose_name='Reconciliation'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('On-Going', 'On-Going'), ('Pending', 'Pending'), ('Ended', 'Ended')], max_length=100, verbose_name='Status'),
        ),
    ]
