# Generated by Django 5.1.1 on 2024-12-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorysnapshot_product_and_more'),
        ('sales', '0012_alter_shift_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_inventory', to='inventory.inventory'),
        ),
    ]
